// ctest unit test for the Cargo.lock producer (framework-free).
#include <cstdio>
#include <string>
#include <vector>

#include "core/model.hpp"
#include "parsers/lockfiles/cargo.hpp"
#include "support/check.hpp"
#include "support/temp_tree.hpp"

using bomwerk::core::Component;
using bomwerk::core::Confidence;
using bomwerk::core::highest_confidence;
using bomwerk::core::Result;
using bomwerk::core::Scope;
using bomwerk::test::TempTree;

namespace cargo_parser = bomwerk::parsers::lockfiles::cargo;

int main()
{
  // Given a Cargo.lock with two registry crates and the workspace's own
  // package (no `source`), when parsed, then the workspace member is skipped,
  // both crates are High confidence and Required, and the registry checksum
  // lands lower-cased in Component::sha256.
  {
    TempTree tree;
    tree.write("Cargo.lock", R"(# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "my-app"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0F1E2D3C4B5A69788796A5B4C3D2E1F00f1e2d3c4b5a69788796a5b4c3d2e1f0"

[[package]]
name = "libc"
version = "0.2.155"
source = "registry+https://github.com/rust-lang/crates.io-index"
)");

    const Result<std::vector<Component>> result = cargo_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 2);
    // Purl-sorted: libc < serde.
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:cargo/libc@0.2.155");
    BOMWERK_TEST_CHECK(result.value[1].purl == "pkg:cargo/serde@1.0.203");
    BOMWERK_TEST_CHECK(result.value[0].scope == Scope::Required);
    BOMWERK_TEST_CHECK(result.value[1].scope == Scope::Required);
    BOMWERK_TEST_CHECK(result.value[0].sha256.empty());
    BOMWERK_TEST_CHECK(result.value[1].sha256 ==
                       "0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0");
    BOMWERK_TEST_CHECK(result.value[1].evidence.size() == 1);
    BOMWERK_TEST_CHECK(result.value[1].evidence[0].detail.find("source registry+") !=
                       std::string::npos);
    BOMWERK_TEST_CHECK(highest_confidence(result.value[1]) == Confidence::High);
  }

  // Given a checksum that is not 64 hex characters, when parsed, then sha256
  // stays empty and the raw checksum is preserved in the evidence detail :
  // honest evidence, never a fake hash field.
  {
    TempTree tree;
    tree.write("Cargo.lock", R"([[package]]
name = "tiny"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "not-a-hash"
)");

    const Result<std::vector<Component>> result = cargo_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].sha256.empty());
    BOMWERK_TEST_CHECK(result.value[0].evidence[0].detail.find("checksum not-a-hash") !=
                       std::string::npos);
  }

  // Given the same crate resolved in two Cargo.lock files (root and a
  // subproject), when parsed, then merge_all folds them into ONE component
  // with both files as evidence.
  {
    TempTree tree;
    const std::string lock_entry = R"([[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"
)";
    tree.write("Cargo.lock", lock_entry);
    tree.write("tool/Cargo.lock", lock_entry);

    const Result<std::vector<Component>> result = cargo_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:cargo/serde@1.0.203");
    BOMWERK_TEST_CHECK(result.value[0].evidence.size() == 2);
  }

  // Given hostile input: a file that is not TOML at all: when parsed, then
  // the producer degrades to exactly one warning and never crashes (rule 1).
  {
    TempTree tree;
    tree.write("Cargo.lock", "{\"this is\": \"json, not toml\"  [[[");

    const Result<std::vector<Component>> result = cargo_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.value.empty());
    BOMWERK_TEST_CHECK(result.warnings.size() == 1);
    BOMWERK_TEST_CHECK(result.warnings[0].message.find("not valid TOML") != std::string::npos);
  }

  // Given package entries missing a name or version, when parsed, then they
  // are counted into one per-file warning and the well-formed entry survives.
  {
    TempTree tree;
    tree.write("Cargo.lock", R"([[package]]
name = "versionless"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
version = "9.9.9"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "kept"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
)");

    const Result<std::vector<Component>> result = cargo_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:cargo/kept@1.0.0");
    BOMWERK_TEST_CHECK(result.warnings.size() == 1);
    BOMWERK_TEST_CHECK(result.warnings[0].message.find("without name/version") !=
                       std::string::npos);
  }

  // Given a package budget of one, when two registry crates are present, then
  // exactly one component is emitted and one limit warning is raised.
  {
    TempTree tree;
    tree.write("Cargo.lock", R"([[package]]
name = "first"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "second"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
)");

    cargo_parser::ParseOptions options;
    options.max_total_packages = 1;
    const Result<std::vector<Component>> result = cargo_parser::parse(tree.root(), options);
    BOMWERK_TEST_CHECK(!result.complete);
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:cargo/first@1.0.0");
    BOMWERK_TEST_CHECK(result.warnings.size() == 1);
    BOMWERK_TEST_CHECK(result.warnings[0].message.find("cargo: package limit 1 reached") !=
                       std::string::npos);

    options.max_total_packages = 2;
    const Result<std::vector<Component>> exact_limit_result =
        cargo_parser::parse(tree.root(), options);
    BOMWERK_TEST_CHECK(exact_limit_result.complete);
    BOMWERK_TEST_CHECK(exact_limit_result.value.size() == 2);
    BOMWERK_TEST_CHECK(exact_limit_result.warnings.empty());
  }

  // Given more Cargo.lock files than a caller-tightened max_scanned_files
  // allows, when parsed, then a warning reports the cap, the run stays
  // complete, and the scanned subset is the path-sorted (deterministic) one.
  {
    TempTree tree;
    tree.write("a/Cargo.lock", R"([[package]]
name = "aaa"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
)");
    tree.write("z/Cargo.lock", R"([[package]]
name = "zzz"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
)");
    cargo_parser::ParseOptions options;
    options.max_scanned_files = 1;
    const auto result = cargo_parser::parse(tree.root(), options);
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(!result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:cargo/aaa@1.0.0");
  }

  std::puts("test_cargo: OK");
  return 0;
}
