// ctest unit test for the yarn.lock producer (framework-free).
// The lockfile shapes below are taken from the 16-repo scan evaluation :
// backstage/cal.com/electron for Berry, gitlabhq/rust for Classic v1: so a
// regression here is a regression against a real repository.
#include <cstdio>
#include <string>
#include <vector>

#include "core/model.hpp"
#include "core/warning.hpp"
#include "parsers/lockfiles/yarn.hpp"
#include "support/check.hpp"
#include "support/temp_tree.hpp"

using bomwerk::core::Component;
using bomwerk::core::Confidence;
using bomwerk::core::highest_confidence;
using bomwerk::core::Result;
using bomwerk::core::Scope;
using bomwerk::test::TempTree;

namespace yarn_parser = bomwerk::parsers::lockfiles::yarn;

namespace
{

/// True when any warning mentions `fragment`: warnings are aggregated per
/// file, so tests assert on content rather than on position.
bool any_warning_contains(const Result<std::vector<Component>>& result, const std::string& fragment)
{
  for (const bomwerk::core::Warning& warning : result.warnings)
  {
    if (warning.message.find(fragment) != std::string::npos)
    {
      return true;
    }
  }
  return false;
}

}  // namespace

int main()
{
  // Given a Yarn Berry lockfile with a scoped package, a plain package and a
  // workspace member, when parsed, then the two registry packages are emitted
  // High confidence with the scope kept as the purl namespace, and the
  // workspace member (the product itself) is skipped SILENTLY, exactly like
  // a rubygems PATH spec: a monorepo declaring itself as a member is normal
  // shape, not a gap worth a warning.
  {
    TempTree tree;
    tree.write("yarn.lock",
               R"(# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@scope/name@npm:^1.2.0":
  version: 1.2.3
  resolution: "@scope/name@npm:1.2.3"
  checksum: 10c0/6eebd12a5cd03cee38fcb915ef9f4ea557df6a06f
  languageName: node
  linkType: hard

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  languageName: node
  linkType: hard

"my-app@workspace:packages/app":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:packages/app"
  languageName: unknown
  linkType: soft
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.value.size() == 2);
    // Purl-sorted: %40scope < left-pad.
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/%40scope/name@1.2.3");
    BOMWERK_TEST_CHECK(result.value[0].name == "@scope/name");
    BOMWERK_TEST_CHECK(result.value[0].version == "1.2.3");
    BOMWERK_TEST_CHECK(result.value[1].purl == "pkg:npm/left-pad@1.3.0");
    BOMWERK_TEST_CHECK(highest_confidence(result.value[0]) == Confidence::High);
    // An npm scope names a real registry-enforced organization, so it
    // doubles as NTIA/CRA supplier evidence; an unscoped package states none.
    BOMWERK_TEST_CHECK(result.value[0].supplier == "scope");
    BOMWERK_TEST_CHECK(result.value[1].supplier.empty());
    // Yarn does not record dev-vs-prod in the lockfile, so nothing is narrowed.
    BOMWERK_TEST_CHECK(result.value[0].scope == Scope::Required);
    BOMWERK_TEST_CHECK(result.value[1].scope == Scope::Required);
    // The sha512-flavoured checksum is evidence, never Component::sha256.
    BOMWERK_TEST_CHECK(result.value[0].sha256.empty());
    BOMWERK_TEST_CHECK(result.warnings.empty());
  }

  // Given link:, portal: and file: locators, when parsed, then: unlike a
  // workspace member: each is skipped and counted into one warning: they can
  // point outside the workspace graph a monorepo itself declares, so
  // surfacing them is worth a sentence even though nothing failed.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(__metadata:
  version: 8

"local-tool@link:../local-tool::locator=app%40workspace%3A.":
  version: 0.0.0-use.local
  resolution: "local-tool@link:../local-tool::locator=app%40workspace%3A."
  linkType: soft

"vendored@portal:../vendored/dist::locator=app%40workspace%3A.":
  version: 1.0.0
  resolution: "vendored@portal:../vendored/dist::locator=app%40workspace%3A."
  linkType: soft

"local-file@file:./vendor/local-file.tgz::locator=app%40workspace%3A.":
  version: 1.0.0
  resolution: "local-file@file:./vendor/local-file.tgz::locator=app%40workspace%3A."
  linkType: soft
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.value.empty());
    BOMWERK_TEST_CHECK(result.warnings.size() == 1);
    BOMWERK_TEST_CHECK(any_warning_contains(result, "3 link/portal/file entrie(s)"));
  }

  // Given an entry key holding several version RANGES, when parsed, then the
  // resolution field decides the identity: a range is a request, not a result.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(__metadata:
  version: 8

"lodash@npm:^4.0.0, lodash@npm:^4.17.0, lodash@npm:~4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  linkType: hard
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/lodash@4.17.21");
  }

  // Given a patched package, when parsed, then the npm locator underneath the
  // patch is recovered (its ':' arrives percent-encoded as %3A) and the patch
  // itself is named in the evidence: a patched dependency is not the pristine
  // registry tarball and the SBOM must not imply it is.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(__metadata:
  version: 8

"fsevents@patch:fsevents@npm%3A2.3.3#optional!builtin<compat/fsevents>::version=2.3.3&hash=df0bf1":
  version: 2.3.3
  resolution: "fsevents@patch:fsevents@npm%3A2.3.3#optional!builtin<compat/fsevents>::version=2.3.3&hash=df0bf1"
  linkType: hard

"@material-ui/pickers@patch:@material-ui/pickers@npm%3A3.3.11#./.yarn/patches/mui.patch::version=3.3.11&hash=5d572b":
  version: 3.3.11
  resolution: "@material-ui/pickers@patch:@material-ui/pickers@npm%3A3.3.11#./.yarn/patches/mui.patch::version=3.3.11&hash=5d572b"
  linkType: hard
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 2);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/%40material-ui/pickers@3.3.11");
    BOMWERK_TEST_CHECK(result.value[1].purl == "pkg:npm/fsevents@2.3.3");
    BOMWERK_TEST_CHECK(result.value[0].evidence[0].detail.find(
                           "(patched: ./.yarn/patches/mui.patch)") != std::string::npos);
    BOMWERK_TEST_CHECK(result.value[1].evidence[0].detail.find(
                           "(patched: optional!builtin<compat/fsevents>)") != std::string::npos);
  }

  // Given an entry's nested dependency map, when parsed, then those edges are
  // never components of their own: only resolutions are.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(__metadata:
  version: 8

"a@npm:1.0.0":
  version: 1.0.0
  resolution: "a@npm:1.0.0"
  dependencies:
    b: "npm:^2.0.0"
    "@scope/c": "npm:^3.0.0"
  peerDependencies:
    react: ^18.0.0
  peerDependenciesMeta:
    react:
      optional: true
  linkType: hard
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/a@1.0.0");
  }

  // Given locators whose protocol has no purl mapping: a git URL, an exec
  // resolution: when parsed, then they are skipped and counted rather than
  // guessed at.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(__metadata:
  version: 8

"pkg@https://github.com/owner/repo.git#commit=abc":
  version: 1.0.0
  resolution: "pkg@https://github.com/owner/repo.git#commit=abc"
  linkType: hard

"gen@exec:./generate.js":
  version: 0.0.0
  resolution: "gen@exec:./generate.js"
  linkType: hard
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.value.empty());
    BOMWERK_TEST_CHECK(any_warning_contains(result, "2 entrie(s) with an unsupported protocol"));
  }

  // Given a Yarn Classic (v1) lockfile: a different, non-YAML format that the
  // banner on line 2 identifies: when parsed, then the name comes from the
  // first descriptor and the version from the quoted `version` line. This is
  // gitlabhq, whose entire npm set was missing from its SBOM before this producer.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scope/pkg@^1.2.3", "@scope/pkg@~1.2.0":
  version "1.2.6"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-1.2.6.tgz#bd9154aec9"
  integrity sha512-1Yjs2SvM8TflER/OD3cOjhWWOZb58A2t7wpE2S9XfBYTiIl+XFhQG2bjy4Pu1I+EA==
  dependencies:
    left-pad "^1.3.0"

left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.npmjs.org/left-pad/-/left-pad-1.3.0.tgz"
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 2);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/%40scope/pkg@1.2.6");
    BOMWERK_TEST_CHECK(result.value[1].purl == "pkg:npm/left-pad@1.3.0");
    BOMWERK_TEST_CHECK(highest_confidence(result.value[0]) == Confidence::High);
    // The nested `dependencies` edge is an edge, not a resolved package.
    BOMWERK_TEST_CHECK(result.value[1].version == "1.3.0");
  }

  // Given a v1 entry whose range itself contains '@': an npm alias: when
  // parsed, then the name splits at the FIRST '@' past a scope, since a range
  // may hold an '@' and a package name may not.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(# yarn lockfile v1

aliased@npm:real-package@^1.0.0:
  version "1.4.0"
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].name == "aliased");
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/aliased@1.4.0");
  }

  // Given a v1 entry that never resolves a version, when parsed, then it is
  // counted into one per-file warning and the good entry still lands.
  {
    TempTree tree;
    tree.write("yarn.lock", R"(# yarn lockfile v1

broken@^1.0.0:
  resolved "https://example.com/broken.tgz"

good@^2.0.0:
  version "2.0.0"
)");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/good@2.0.0");
    BOMWERK_TEST_CHECK(result.warnings.size() == 1);
    BOMWERK_TEST_CHECK(any_warning_contains(result, "1 entrie(s) without a resolved version"));
  }

  // Given a file named yarn.lock that is neither generation, when parsed, then
  // the run says so instead of reporting an empty dependency set as a clean
  // one: the unparsed-manifest rule applied inside the parser.
  {
    TempTree tree;
    tree.write("yarn.lock", "this is not a lockfile at all\n");

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.value.empty());
    BOMWERK_TEST_CHECK(any_warning_contains(result, "unrecognized lockfile format"));
  }

  // Given hostile input: binary garbage with no recognizable structure: when
  // parsed, then the producer stays complete and never crashes (rule 1).
  {
    TempTree tree;
    // Explicit length: the embedded NUL must reach the file, not truncate the
    // C-string literal.
    const std::string binary_garbage("\x00\x01\x02 garbage \xff\xfe\n__metadata:\n  x\n", 31);
    tree.write("yarn.lock", binary_garbage);

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(result.value.empty());
  }

  // Given the same package resolved in two lockfiles: a Berry monorepo with a
  // nested workspace lock, which is backstage's shape: when parsed, then
  // merge_all folds them into ONE component carrying both files as evidence.
  {
    TempTree tree;
    const std::string lock_contents = R"(__metadata:
  version: 8

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  linkType: hard
)";
    tree.write("yarn.lock", lock_contents);
    tree.write("microsite/yarn.lock", lock_contents);

    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/left-pad@1.3.0");
    BOMWERK_TEST_CHECK(result.value[0].evidence.size() == 2);
  }

  // Given a package budget smaller than the lockfile, when parsed, then the
  // limit is reported once and the run degrades to a partial SBOM rather than
  // failing: partial output beats none (rule 1).
  {
    TempTree tree;
    tree.write("yarn.lock", R"(__metadata:
  version: 8

"a@npm:1.0.0":
  resolution: "a@npm:1.0.0"

"b@npm:2.0.0":
  resolution: "b@npm:2.0.0"

"c@npm:3.0.0":
  resolution: "c@npm:3.0.0"
)");

    yarn_parser::ParseOptions options;
    options.max_total_packages = 2;
    const Result<std::vector<Component>> result = yarn_parser::parse(tree.root(), options);
    BOMWERK_TEST_CHECK(!result.complete);
    BOMWERK_TEST_CHECK(result.value.size() == 2);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/a@1.0.0");
    BOMWERK_TEST_CHECK(result.value[1].purl == "pkg:npm/b@2.0.0");
    BOMWERK_TEST_CHECK(any_warning_contains(result, "yarn: package limit 2 reached"));

    options.max_total_packages = 3;
    const Result<std::vector<Component>> exact_limit_result =
        yarn_parser::parse(tree.root(), options);
    BOMWERK_TEST_CHECK(exact_limit_result.complete);
    BOMWERK_TEST_CHECK(exact_limit_result.value.size() == 3);
    BOMWERK_TEST_CHECK(exact_limit_result.warnings.empty());
  }

  // Given more yarn.lock files than a caller-tightened max_scanned_files
  // allows, when parsed, then a warning reports the cap, the run stays
  // complete, and the scanned subset is the path-sorted (deterministic) one.
  {
    TempTree tree;
    tree.write("a/yarn.lock", R"(# yarn lockfile v1

aaa@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/aaa/-/aaa-1.0.0.tgz"
)");
    tree.write("z/yarn.lock", R"(# yarn lockfile v1

zzz@^1.0.0:
  version "1.0.0"
  resolved "https://registry.npmjs.org/zzz/-/zzz-1.0.0.tgz"
)");
    yarn_parser::ParseOptions options;
    options.max_scanned_files = 1;
    const auto result = yarn_parser::parse(tree.root(), options);
    BOMWERK_TEST_CHECK(result.complete);
    BOMWERK_TEST_CHECK(!result.warnings.empty());
    BOMWERK_TEST_CHECK(result.value.size() == 1);
    BOMWERK_TEST_CHECK(result.value[0].purl == "pkg:npm/aaa@1.0.0");
  }

  std::puts("test_yarn: OK");
  return 0;
}
