// ctest unit test for --license-fallback-timeout/--license-cache-max-age CLI wiring, plus
// the exit-code regression guard for a timed-out (but complete) license-fallback pass. Command
// sources are linked directly (same precedent as test_fail_on_cli.cpp) since CLI command
// implementations are intentionally not a production library.
#include <CLI/CLI.hpp>
#include <cstdlib>
#include <filesystem>
#include <string>

#include "cli/scan_command.hpp"
#include "core/exit_codes.hpp"
#include "support/check.hpp"
#include "support/temp_tree.hpp"

namespace core = bomwerk::core;

using bomwerk::cli::register_scan_command;
using bomwerk::cli::run_scan;
using bomwerk::cli::ScanOptions;
using bomwerk::test::TempTree;

int main()
{
  // Given --license-fallback-timeout typed on the command line, when scan's command line is
  // parsed, then the seconds value and the "given" flag are both set; omitted, "given" stays
  // false so 0 can mean "not requested" rather than "requested, zero seconds".
  {
    CLI::App app;
    ScanOptions options;
    register_scan_command(app, options);
    app.parse("scan . --license-fallback --license-fallback-timeout 60");
    BOMWERK_TEST_CHECK(options.license_fallback_timeout_seconds == 60);
    BOMWERK_TEST_CHECK(options.license_fallback_timeout_given);
  }
  {
    CLI::App app;
    ScanOptions options;
    register_scan_command(app, options);
    app.parse("scan . --license-fallback");
    BOMWERK_TEST_CHECK(!options.license_fallback_timeout_given);
  }

  // Given --license-cache-max-age 0 typed explicitly, when parsed, then the "given" flag
  // distinguishes an explicit zero (force a refetch) from the flag never having been typed.
  {
    CLI::App app;
    ScanOptions options;
    register_scan_command(app, options);
    app.parse("scan . --license-fallback --license-cache-max-age 0");
    BOMWERK_TEST_CHECK(options.license_cache_max_age_seconds == 0);
    BOMWERK_TEST_CHECK(options.license_cache_max_age_given);
  }
  {
    CLI::App app;
    ScanOptions options;
    register_scan_command(app, options);
    app.parse("scan . --license-fallback");
    BOMWERK_TEST_CHECK(!options.license_cache_max_age_given);
  }

  // Given a repo with one unlicensed, exact-version cargo dependency and
  // --license-fallback-timeout 0, when scan runs, then the zero budget expires before
  // enrich_component_licenses issues its first request (no real network call happens), the
  // component is left unenriched and warned about, and the exit code stays
  // completed-with-warnings: never incomplete. This is the regression guard for the explicit
  // "MUST stay on exit 1" requirement.
  //
  // scan_command.cpp always leaves LicenseEnrichmentOptions::cache_database_path empty, so a
  // plain run_scan() call resolves the REAL, persistent, shared vuln cache
  // (default_cache_database_path(), under $XDG_CACHE_HOME or $HOME/.cache): a purl this test
  // has ever fetched for real elsewhere would already answer from a fresh cache hit and never
  // reach the zero-budget deadline at all. XDG_CACHE_HOME is redirected into this TempTree (the
  // same setenv/unsetenv pattern test_coverage_report.cpp/test_cyclonedx.cpp use for
  // SOURCE_DATE_EPOCH) so this stays hermetic and idempotent across repeated runs.
  {
    TempTree tree;
    tree.write("Cargo.lock", R"(# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "demo-rust-app"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5f0e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0"
)");

    ScanOptions options;
    options.root_directory = tree.root();
    options.output_path = tree.root() / "sbom.cdx.json";
    options.vuln_enabled = false;
    options.license_fallback = true;
    options.license_fallback_timeout_given = true;
    options.license_fallback_timeout_seconds = 0;

    setenv("XDG_CACHE_HOME", (tree.root() / "xdg-cache").string().c_str(), 1);
    const int exit_code = run_scan(options);
    unsetenv("XDG_CACHE_HOME");

    BOMWERK_TEST_CHECK(exit_code == core::kExitCompletedWithWarnings);
  }

  return 0;
}
